version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:3.0.3-node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd todo-app
            gem install bundler -v 2.4.22
            bundle config set --local path 'vendor/bundle'
            bundle install
      - save_cache:
          key: gem-cache-{{ .Branch }}-{{ checksum "todo-app/Gemfile.lock" }}
          paths:
            - vendor/bundle

  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: |
            docker build -t JamesGraham97/my_rails_app:$(echo ${CIRCLE_SHA1} | tr '[:upper:]' '[:lower:]') .
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
          docker push JamesGraham97/my_rails_app:$(echo ${CIRCLE_SHA1} | tr '[:upper:]' '[:lower:]')

  approval:
    docker:
      - image: circleci/ruby:3.0.3-node  # Use the same image as the build job
    steps:
      - checkout
      - run:
          name: Manual Approval
          command: echo "Manual approval required"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
      - approval:
          type: approval
          requires:
            - deploy
