version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:3.0.3-node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd todo-app
            gem install bundler -v 2.4.22
            bundle config set --local path 'vendor/bundle'
            bundle install
      - save_cache:
          key: gem-cache-{{ .Branch }}-{{ checksum "todo-app/Gemfile.lock" }}
          paths:
            - todo-app/vendor/bundle
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            cd todo-app
            docker build -t jamesgraham97/my_rails_app:${CIRCLE_SHA1} .
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker push jamesgraham97/my_rails_app:${CIRCLE_SHA1}
      - run:
          name: Cleanup Docker Resources
          command: |
            docker container prune -f
            docker image prune -a -f
            docker volume prune -f
            docker network prune -f

  deploy:
    docker:
      - image: circleci/ruby:3.0.3-node
    steps:
      - checkout
      - run:
          name: Create .ssh directory and set permissions
          command: |
            mkdir -p ~/.ssh
            chmod 700 ~/.ssh
            touch ~/.ssh/known_hosts
            chmod 600 ~/.ssh/known_hosts
            ssh-keyscan -H $EC2_PUBLIC_DNS >> ~/.ssh/known_hosts
      - run:
          name: Stop existing Docker container on port 80
          command: |
            echo "$SSH_PRIVATE_KEY" | ssh -o StrictHostKeyChecking=no -i /dev/stdin $EC2_USERNAME@$EC2_PUBLIC_DNS "docker ps -q --filter 'publish=80' | xargs -r docker stop || true"
      - run:
          name: Remove existing Docker container on port 80
          command: |
            echo "$SSH_PRIVATE_KEY" | ssh -o StrictHostKeyChecking=no -i /dev/stdin $EC2_USERNAME@$EC2_PUBLIC_DNS "docker ps -aq --filter 'publish=80' | xargs -r docker rm || true"
      - run:
          name: Deploy to EC2
          command: |
            cd todo-app
            echo "$SSH_PRIVATE_KEY" | ssh -o StrictHostKeyChecking=no -i /dev/stdin $EC2_USERNAME@$EC2_PUBLIC_DNS "/usr/bin/docker pull jamesgraham97/my_rails_app:$(echo ${CIRCLE_SHA1} | tr '[:upper:]' '[:lower:]')"
            echo "$SSH_PRIVATE_KEY" | ssh -o StrictHostKeyChecking=no -i /dev/stdin $EC2_USERNAME@$EC2_PUBLIC_DNS "/usr/bin/docker run -d -p 80:3000 jamesgraham97/my_rails_app:$(echo ${CIRCLE_SHA1} | tr '[:upper:]' '[:lower:]')"
      - run:
          name: Wait for container to initialize
          command: sleep 30
      - run:
          name: Run pending migrations on EC2
          command: |
            echo "$SSH_PRIVATE_KEY" | ssh -o StrictHostKeyChecking=no -i /dev/stdin $EC2_USERNAME@$EC2_PUBLIC_DNS "docker exec -it \$(docker ps -q --filter ancestor=jamesgraham97/my_rails_app) bin/rails db:migrate RAILS_ENV=production"

  approval:
    docker:
      - image: circleci/ruby:3.0.3-node
    steps:
      - checkout
      - run:
          name: Manual Approval
          command: echo "Manual approval required"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - hold_for_approval:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold_for_approval
